// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/dysodeng/ai-adp/internal/application/tenant/service"
	service2 "github.com/dysodeng/ai-adp/internal/domain/agent/service"
	"github.com/dysodeng/ai-adp/internal/domain/shared/port"
	"github.com/dysodeng/ai-adp/internal/infrastructure/ai/engine"
	"github.com/dysodeng/ai-adp/internal/infrastructure/config"
	"github.com/dysodeng/ai-adp/internal/infrastructure/persistence/repository/app"
	modelrepo "github.com/dysodeng/ai-adp/internal/infrastructure/persistence/repository/model"
	"github.com/dysodeng/ai-adp/internal/infrastructure/persistence/repository/tenant"
	"github.com/dysodeng/ai-adp/internal/infrastructure/server"
	"github.com/dysodeng/ai-adp/internal/interfaces/http/handler"
)

// Injectors from wire.go:

func InitApp(configPath string) (*App, error) {
	configConfig, err := config.Load(configPath)
	if err != nil {
		return nil, err
	}
	db, err := provideDB(configConfig)
	if err != nil {
		return nil, err
	}
	tenantRepositoryImpl := tenant.NewTenantRepository(db)
	tenantAppService := service.NewTenantAppService(tenantRepositoryImpl)
	tenantHandler := handler.NewTenantHandler(tenantAppService)
	httpServer := server.NewHTTPServer(configConfig, tenantHandler)
	executorFactory := engine.NewExecutorFactory()
	appRepositoryImpl := app.NewAppRepository(db)
	logger, err := provideLogger(configConfig)
	if err != nil {
		return nil, err
	}
	shutdownFunc, err := provideTracerShutdown(configConfig)
	if err != nil {
		return nil, err
	}
	toolService := port.NewMockToolService()
	agentBuilder := service2.NewAgentBuilder(toolService)
	modelConfigRepositoryImpl := modelrepo.NewModelConfigRepository(db)
	agentFactory := provideAgentFactory(modelConfigRepositoryImpl)
	diApp := NewApp(httpServer, executorFactory, appRepositoryImpl, logger, shutdownFunc, toolService, agentBuilder, agentFactory)
	return diApp, nil
}
