// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"

	"github.com/dysodeng/ai-adp/internal/application/chat/orchestrator"
	service3 "github.com/dysodeng/ai-adp/internal/application/chat/service"
	"github.com/dysodeng/ai-adp/internal/application/tenant/service"
	"github.com/dysodeng/ai-adp/internal/di/provider"
	service2 "github.com/dysodeng/ai-adp/internal/domain/agent/service"
	"github.com/dysodeng/ai-adp/internal/domain/shared/port"
	"github.com/dysodeng/ai-adp/internal/infrastructure/agent/cancel"
	"github.com/dysodeng/ai-adp/internal/infrastructure/agent/stream"
	"github.com/dysodeng/ai-adp/internal/infrastructure/persistence/repository/app"
	"github.com/dysodeng/ai-adp/internal/infrastructure/persistence/repository/model"
	"github.com/dysodeng/ai-adp/internal/infrastructure/persistence/repository/tenant"
	"github.com/dysodeng/ai-adp/internal/interfaces/http"
	"github.com/dysodeng/ai-adp/internal/interfaces/http/handler"
)

// Injectors from wire.go:

func InitApp(ctx context.Context) (*App, error) {
	config, err := provider.ProvideConfig()
	if err != nil {
		return nil, err
	}
	monitor, err := provider.ProvideMonitor(config)
	if err != nil {
		return nil, err
	}
	logger, err := provider.ProvideLogger(config)
	if err != nil {
		return nil, err
	}
	transactionManager, err := provider.ProvideDB(ctx, config)
	if err != nil {
		return nil, err
	}
	client, err := provider.ProvideRedis(config)
	if err != nil {
		return nil, err
	}
	cache, err := provider.ProvideCache(config)
	if err != nil {
		return nil, err
	}
	tenantRepository := tenant.NewTenantRepository(transactionManager)
	tenantService := service.NewTenantAppService(tenantRepository)
	tenantHandler := handler.NewTenantHandler(tenantService)
	toolService := port.NewMockToolService()
	agentBuilder := service2.NewAgentBuilder(toolService)
	modelConfigRepository := model.NewModelConfigRepository(transactionManager)
	agentFactory := provider.ProvideAgentFactory(modelConfigRepository)
	taskRegistry := cancel.NewMemoryTaskRegistry()
	memoryExecutorRegistry := stream.NewMemoryExecutorRegistry()
	executorOrchestrator := orchestrator.NewExecutorOrchestrator(agentBuilder, agentFactory, taskRegistry, memoryExecutorRegistry)
	appRepository := app.NewAppRepository(transactionManager)
	redisEventStore := provideRedisEventStore(client)
	chatAppService := service3.NewChatAppService(executorOrchestrator, appRepository, redisEventStore, memoryExecutorRegistry)
	chatHandler := handler.NewChatHandler(chatAppService)
	cancelBroadcaster := cancel.NewRedisCancelBroadcaster(client)
	cancelHandler := handler.NewCancelHandler(taskRegistry, cancelBroadcaster)
	handlerRegistry := http.NewHandlerRegistry(tenantHandler, chatHandler, cancelHandler)
	server := provider.ProvideHTTPServer(config, handlerRegistry)
	healthServer := provider.ProvideHealthServer(config)
	gatewayRegistry, err := provider.ProvideGatewayRegistry(config)
	if err != nil {
		return nil, err
	}
	diApp := NewApp(config, monitor, logger, transactionManager, client, cache, handlerRegistry, server, healthServer, toolService, agentBuilder, agentFactory, cancelBroadcaster, taskRegistry, gatewayRegistry)
	return diApp, nil
}
